### ISSUE TITLE
Is it possible to add a nuget package link if needed

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/apisof.net#69]
Some APIs may already be included into the framework references, some may not be available for the framework, it would be convenient to get the NuGet package if has a link.

For example, this `Meter.CreateGauge` API is introduced in dotnet 9, included into dotnet 9 framework reference, while not included for previous framework references, it would be geat to have a nuget package name or link to use.

![Image](https://github.com/user-attachments/assets/13dd1cf1-a5dc-4a2c-99dc-3c76ce4eaeae)

**Comment by terrajobst** [comment]
@WeihanLi the web site presents the reference information based on the selected framework. In your case, `net9.0` is selected, which is why it's underlined. The deep purple indicates the API is indeed in-box.

If you click on any of the light color boxes (the one where the API isn't in-box) you'll see the package you need to reference:

![Image](https://github.com/user-attachments/assets/97ca8d4a-ca4d-43f6-8bf3-d9b784658d42)
